const citiesTypes = {
    // GET_CITIES_START: "GET_CITIES_START",
    GET_CITIES: "GET_CITIES",
    SET_CITIES: 'SET_CITIES',
    // GET_PATH_CITIES_START: "GET_PATH_CITIES_START",
    GET_PATH_CITIES: "GET_PATH_CITIES",
    SET_PATH_CITIES: "SET_PATH_CITIES"
};

export default citiesTypes;